resource_rules:
  issues:
    rules:
      - name: Triage policy
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: days
            interval: 30
          state: opened
          no_additional_labels: true
        limits:
          most_recent: 50
        actions:
          labels:
            - needs attention
          comment: |
            Hi {{author}},

            Thank you for raising an issue to help improve Remmina. We're sorry this particular issue has gone unnoticed for quite some time.
            
            This issue will be threated as soon as possible.
            We'd like to ask you to help us keep our issue tracker organized by determining whether this issue should be closed or adding additional details.

            If this issue is reporting a bug, let us know if this issue is still present in a newer version and if you can reproduce it.

            Thanks for your help!
            
            ---
            This is an automatic message. If you have suggestions to improve this automatic action feel free to add a comment on https://gitlab.com/Remmina/Remmina/-/issues/2407

            /cc {{assignees}} @kingu @antenore

          summarize:
            title: |
              #{resource[:type].capitalize} require labels
            item: |
              - [ ] [{{title}}]({{web_url}}) {{labels}}
            redact_confidential_resources: false
            summary: |
              The following issues require labels:

              {{items}}

              Please take care of them.

              /label ~"needs attention"

      - name: Close old needinfo policy
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 1
          state: opened
          labels:
            - needinfo
        limits:
          most_recent: 50
        actions:
          status: close
          comment: |
            Hi {{author}},

            Thank you for raising an issue to help improve Remmina. We're sorry this particular issue has gone unnoticed for quite some time.
            
            This issue will be closed, as it meets the following criteria:
            * No activity in the past 1 months.
           
            We'd like to ask you to help us keep our issue tracker organized  by determining whether this issue should be reopened.

            If this issue is reporting a bug, let us know if this issue is still present in a newer version and if you can reproduce it.

            Thanks for your help!

            ---
            This is an automatic message. If you have suggestions to improve this automatic action feel free to add a comment on https://gitlab.com/Remmina/Remmina/-/issues/2407

            /cc {{assignees}}

      - name: Close old needs attention policy
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 2
          state: opened
          labels:
            - needs attention
        limits:
          most_recent: 50
        actions:
          status: close
          comment: |
            Hi {{author}},

            Thank you for raising an issue to help improve Remmina. We're sorry this particular issue has gone unnoticed for quite some time.
            
            This issue will be closed, as it meets the following criteria:
            * No activity in the past 1 months.
           
            We'd like to ask you to help us keep our issue tracker organized  by determining whether this issue should be reopened.

            If this issue is reporting a bug, let us know if this issue is still present in a newer version and if you can reproduce it.

            Thanks for your help!

            ---
            This is an automatic message. If you have suggestions to improve this automatic action feel free to add a comment on https://gitlab.com/Remmina/Remmina/-/issues/2407

            /cc {{assignees}}

  merge_requests:
    rules:
      - name: Close old WIP policy
        conditions:
          title: WIP
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 4
          state: opened
          no_additional_labels: true
        limits:
          most_recent: 50
        actions:
          status: close
          comment: |
            {{author}} This merge request is marked as work in progress with no update for very long time. We are now closing it, but please re-open if you are still interested in finishing this merge request.
            CC {{assignees}}
